// <auto-generated />
using System;
using Dukkantek.Inventory.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dukkantek.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20220517074112_initialcreation")]
    partial class initialcreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dukkantek.Inventory.Model.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Category 1"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Category 2"
                        });
                });

            modelBuilder.Entity("Dukkantek.Inventory.Model.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Barcode = "123456789",
                            CategoryId = 1L,
                            Description = "Product 1 Description",
                            Name = "Product 1",
                            Status = "Sold",
                            Weight = "0.95 kg"
                        },
                        new
                        {
                            Id = 2L,
                            Barcode = "123456789",
                            CategoryId = 2L,
                            Description = "Product 2 Description",
                            Name = "Product 2",
                            Status = "Sold",
                            Weight = "0.75 kg"
                        },
                        new
                        {
                            Id = 3L,
                            Barcode = "123456789",
                            CategoryId = 1L,
                            Description = "Product 3 Description",
                            Name = "Product 3",
                            Status = "Sold",
                            Weight = "0.70 kg"
                        },
                        new
                        {
                            Id = 4L,
                            Barcode = "123456789",
                            CategoryId = 2L,
                            Description = "Product 4 Description",
                            Name = "Product 4",
                            Status = "InStock",
                            Weight = "2 kg"
                        },
                        new
                        {
                            Id = 5L,
                            Barcode = "123456789",
                            CategoryId = 1L,
                            Description = "Product 5 Description",
                            Name = "Product 5",
                            Status = "InStock",
                            Weight = "1.5 kg"
                        },
                        new
                        {
                            Id = 6L,
                            Barcode = "123456789",
                            CategoryId = 2L,
                            Description = "Product 6 Description",
                            Name = "Product 6",
                            Status = "InStock",
                            Weight = "2 kg"
                        },
                        new
                        {
                            Id = 7L,
                            Barcode = "123456789",
                            CategoryId = 1L,
                            Description = "Product 7 Description",
                            Name = "Product 7",
                            Status = "InStock",
                            Weight = "0.5 kg"
                        },
                        new
                        {
                            Id = 8L,
                            Barcode = "123456789",
                            CategoryId = 2L,
                            Description = "Product 8 Description",
                            Name = "Product 8",
                            Status = "InStock",
                            Weight = "1.5 kg"
                        },
                        new
                        {
                            Id = 9L,
                            Barcode = "123456789",
                            CategoryId = 1L,
                            Description = "Product 9 Description",
                            Name = "Product 9",
                            Status = "InStock",
                            Weight = "2.75 kg"
                        },
                        new
                        {
                            Id = 10L,
                            Barcode = "123456789",
                            CategoryId = 2L,
                            Description = "Product 10 Description",
                            Name = "Product 10",
                            Status = "Damaged",
                            Weight = "0.65 kg"
                        });
                });

            modelBuilder.Entity("Dukkantek.Inventory.Model.Entities.Product", b =>
                {
                    b.HasOne("Dukkantek.Inventory.Model.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Dukkantek.Inventory.Model.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
